sudo: false
install: true
language: java

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk version
  - mkdir -p "$HOME/.sdkman/etc"
  - echo "sdkman_auto_answer=true" > "$HOME/.sdkman/etc/config"
  - echo "sdkman_auto_selfupdate=true" >> "$HOME/.sdkman/etc/config"
  - sdk install java 8.0.181-zulu
  - sdk use java 8.0.181-zulu
  - java -version

script:
  - ./gradlew clean check

after_success:
  - ./gradlew jacocoTestReportCodacyUpload
