spring:
  application:
    name: atomix-boot-node
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    consul:
      enabled: false
    zookeeper:
      enabled: false

server:
  port: 0

management:
  endpoints:
    enabled-by-default: false
    health:
      enabled: true

logging:
  level:
    io.atomix: INFO
    com.github.lburgazzoli.atomix: DEBUG

atomix:
  local-member:
    id: ${spring.application.name}-${random.uuid}
    type: EPHEMERAL
    address: ${node.ip:localhost}:${node.port:8700}
  cluster:
    name: ${spring.application.name}
  profiles:
    - DATA_GRID