spring:
  application:
    name: atomix-boot-node
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
      enabled: true

server:
  port: 0

management:
  endpoints:
    enabled-by-default: false
    health:
      enabled: true

logging:
  level:
    io.atomix: INFO
    com.github.lburgazzoli.atomix: DEBUG

atomix:
  node:
    data-directory: ${java.io.tmpdir}/${atomix.node.local-node.id}
    local-node:
      id: ${spring.application.name}-${random.uuid}
      type: core
      address: ${node.ip:localhost}:${node.port:8700}
    cluster:
      name: ${spring.application.name}
    partition-groups:
      primary-backup:
        - name: "pb"
          partitions: 3
