---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: atomix
    name: atomix
  spec:
    clusterIP: None
    ports:
    - port: 5679
    selector:
      app: atomix
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: atomix
  spec:
    serviceName: "atomix"
    replicas: 2
    selector:
      matchLabels:
        app: atomix
    template:
      metadata:
        labels:
          app: atomix
      spec:
        containers:
        - name: atomix
          image: lburgazzoli/atomix-boot:3.0.3
          imagePullPolicy: Always
          ports:
          - containerPort: 5679
            name: atomix
          env:
          - name: ATOMIX_ENABLED
            value: "true"
          - name: ATOMIX_CLUSTER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ATOMIX_MEMBER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ATOMIX_MEMBER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ATOMIX_MEMBER_PORT
            value: "5679"
          - name: ATOMIX_DISCOVERY_K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ATOMIX_DISCOVERY_K8S_ENABLED
            value: "true"
          - name: ATOMIX_DISCOVERY_K8S_ENDPOINT_NAME
            value: "atomix"
          - name: ATOMIX_DISCOVERY_K8S_PORT_NAME
            value: "atomix"